#![cfg(feature = "clob")]
#![allow(
    clippy::unwrap_used,
    reason = "Test code — unwrap is fine for fixture loading and assertions"
)]

//! CR-9: build_v2 on OrderBuilder<Market, _> produces SignableOrderV2
//! matching py SDK reference output for V2 market buys.
//!
//! Fixture: tests/fixtures/order_v2_market_buy.json (generated by
//! tests/fixtures/gen_order_v2_market_buy.py using py-clob-client-v2).
//!
//! Scenario: BUY $100 USDC of YES tokens at price $0.33 (non-clean-divisor), FOK, tick_size=0.01.
//!
//! Price 0.33 exercises the C-1 bug class: 100 USDC / 0.33 = 303.0303... shares (truncated).
//! Without the maker_amount_override fix:
//!   maker_amount = size * price = 303.0303 * 0.33 = 99.999999 → 99_999_900 (one tick short)
//! With the fix (py SDK authoritative behavior):
//!   maker_amount = round_down(usdc_input, lot) = 100.0 → 100_000_000 (exact user input)
//!
//! Expected amounts from py SDK:
//!   - makerAmount = 100_000_000 (100 USDC, 6 decimals — user's exact input)
//!   - takerAmount = 303_030_300 (303.0303 shares, 6 decimals)
//!   - expiration = "0"    (market orders fill immediately or cancel)
//!   - post_only absent / false
//!   - timestamp = 1_800_000_000_000 (pinned ms)
//!
//! The Rust cross-check calls assemble_signable_order_v2 directly (bypassing
//! the async tick_size network fetch and calculate_price orderbook call) with
//! pre-derived inputs and the maker_amount_override, mirroring the pattern
//! from v2_timestamp_ms.rs and v2_expiration_threading.rs.

use alloy::primitives::{Address, FixedBytes, U256};
use polymarket_client_sdk::clob::order_builder::assemble_signable_order_v2;
use polymarket_client_sdk::clob::types::{OrderType, Side, SignatureType};
use rust_decimal_macros::dec;
use serde_json::Value;

const FIXTURE: &str = include_str!("fixtures/order_v2_market_buy.json");
const PINNED_MS: i64 = 1_800_000_000_000;

// ── Test 1: fixture is well-formed ────────────────────────────────────────────

/// Sanity-check that the py SDK fixture contains expected field values before
/// the Rust cross-check test runs. If this test fails, regenerate the fixture.
#[test]
fn v2_market_buy_fixture_is_well_formed() {
    let fixture: Value = serde_json::from_str(FIXTURE)
        .expect("order_v2_market_buy.json must be valid JSON");

    let signed = &fixture["signed_order"];

    // side: BUY = 0
    assert_eq!(
        signed["side"].as_u64().unwrap_or(999),
        0,
        "BUY = 0"
    );

    // price: 0.33 (non-clean-divisor — exercises the C-1 bug class)
    assert_eq!(
        fixture["price"].as_f64().unwrap_or(0.0),
        0.33,
        "fixture must use price=0.33 to exercise the non-clean-divisor path"
    );

    // makerAmount: 100 USDC = 100_000_000 at 6 decimals (user's exact input, not size*price)
    assert_eq!(
        signed["makerAmount"].as_str().unwrap_or(""),
        "100000000",
        "makerAmount must be 100_000_000 (100 USDC — user's exact input)"
    );

    // takerAmount: 303.0303 shares = 303_030_300 at 6 decimals
    assert_eq!(
        signed["takerAmount"].as_str().unwrap_or(""),
        "303030300",
        "takerAmount must be 303_030_300 (303.0303 shares)"
    );

    // timestamp must be in milliseconds (well above any seconds-era value)
    let ts_str = signed["timestamp"].as_str().expect("timestamp must be string");
    let ts_u64: u64 = ts_str.parse().expect("timestamp must be numeric string");
    assert_eq!(
        ts_u64,
        1_800_000_000_000u64,
        "timestamp must equal pinned ms value"
    );
    assert!(
        ts_u64 > 1_500_000_000_000,
        "timestamp must be in ms range; got {ts_u64}"
    );

    // expiration must be "0" for market orders
    let exp_str = signed["expiration"]
        .as_str()
        .map(|s| s.to_owned())
        .or_else(|| signed["expiration"].as_u64().map(|n| n.to_string()))
        .expect("expiration must be string or integer");
    assert_eq!(exp_str, "0", "market orders must have expiration = 0");

    // pinned_ms_timestamp top-level key
    assert_eq!(
        fixture["pinned_ms_timestamp"].as_u64().unwrap_or(0),
        1_800_000_000_000u64,
        "pinned_ms_timestamp must equal the pinned value"
    );
}

// ── Test 2: Non-clean-divisor: maker_amount_override produces correct amounts ─

/// Cross-check that assemble_signable_order_v2 with the maker_amount_override
/// yields the same makerAmount, takerAmount, expiration, and timestamp as the
/// py SDK for a non-clean-divisor price.
///
/// Market BUY $100 USDC at price $0.33, tick_size=0.01 (non-clean-divisor):
///   size (shares) = trunc(100 / 0.33, 2+2=4) = 303.0303
///   Without override: maker = 303.0303 * 0.33 = 99.999999 → 99_999_900 (BUG)
///   With override:    maker = 100.000000 → 100_000_000 (CORRECT, matches py SDK)
///   taker = 303.0303 → 303_030_300
///
/// This test catches regression of the C-1 bug: if the override is not passed,
/// the makerAmount will be 99_999_900 instead of 100_000_000.
#[test]
fn v2_market_buy_amounts_match_fixture() {
    let price = dec!(0.33);
    let minimum_tick_size = dec!(0.01);
    let decimals = minimum_tick_size.scale(); // 2
    // Simulate what build_v2 BUY+USDC computes:
    //   size = trunc(100 / 0.33, decimals + LOT_SIZE_SCALE) = trunc(303.0303..., 4) = 303.0303
    let size = dec!(303.0303);

    // maker_amount_override: user's exact 100 USDC input scaled to 6 decimals.
    // This is what build_v2 computes as raw_maker_u256 for BUY+USDC.
    let maker_amount_override = Some(U256::from(100_000_000u64));

    let _ = decimals; // suppress unused warning; used implicitly via size derivation above

    let result = assemble_signable_order_v2(
        U256::from(12345678901234567890u128), // token_id (matches fixture)
        Side::Buy,
        price,
        size,
        minimum_tick_size,
        OrderType::FOK,      // market orders use FOK or FAK; fixture uses FOK
        false,               // post_only: market orders are never post-only
        || 1_234_567_890u64, // salt (pinned)
        || PINNED_MS,        // timestamp_ms_source (pinned)
        None,                // funder = signer
        Address::ZERO,       // signer (not testing signing here)
        SignatureType::Eoa,
        FixedBytes::<32>::ZERO, // metadata
        FixedBytes::<32>::ZERO, // builder
        U256::ZERO,             // expiration = 0 (market orders)
        maker_amount_override,  // BUY+USDC: user's exact USDC input, not size*price
    )
    .expect("assemble_signable_order_v2 must succeed with valid market-buy inputs");

    // takerAmount = shares received (BUY takes tokens) = 303.0303 shares
    assert_eq!(
        result.order.takerAmount,
        U256::from(303_030_300u64),
        "takerAmount must be 303_030_300 (303.0303 shares at 6 decimals)"
    );

    // makerAmount = USDC spent (BUY makes USDC payment) = user's exact 100 USDC input.
    // A regression of the override would yield 99_999_900 here instead of 100_000_000.
    assert_eq!(
        result.order.makerAmount,
        U256::from(100_000_000u64),
        "makerAmount must be 100_000_000 (100 USDC — user's exact input, not size*price)"
    );

    // expiration must be U256::ZERO (market orders fill immediately or cancel)
    assert_eq!(
        result.expiration,
        U256::ZERO,
        "V2 market order expiration must be U256::ZERO"
    );

    // post_only must be false (market orders are never post-only)
    assert_eq!(
        result.post_only,
        Some(false),
        "V2 market order post_only must be Some(false)"
    );

    // timestamp must be the pinned ms value (not seconds)
    assert_eq!(
        result.order.timestamp,
        U256::from(1_800_000_000_000u64),
        "order.timestamp must equal pinned ms value; a revert to seconds would fail"
    );

    // order_type must be FOK (as specified)
    assert!(
        matches!(result.order_type, OrderType::FOK),
        "order_type must be FOK"
    );

    // side must be BUY = 0
    assert_eq!(result.order.side, 0u8, "side must be BUY = 0");
}

// ── Test 3: Regression guard — without override, non-clean-divisor loses a tick ──

/// Negative test: confirm that WITHOUT the maker_amount_override, the BUY+USDC
/// non-clean-divisor path produces the wrong (pre-fix) maker_amount.
///
/// This test documents the C-1 bug and ensures the override is load-bearing.
/// If assemble_signable_order_v2 somehow fixes the bug internally without the
/// override, this test would fail — which would mean the override is redundant
/// and the fix lives elsewhere. That would still be correct behavior, just
/// documented differently.
#[test]
fn v2_market_buy_without_override_loses_one_tick() {
    let price = dec!(0.33);
    let minimum_tick_size = dec!(0.01);
    let size = dec!(303.0303); // trunc(100 / 0.33, 4) = 303.0303 shares

    let result = assemble_signable_order_v2(
        U256::from(1u64),
        Side::Buy,
        price,
        size,
        minimum_tick_size,
        OrderType::FOK,
        false,
        || 1u64,
        || PINNED_MS,
        None,
        Address::ZERO,
        SignatureType::Eoa,
        FixedBytes::<32>::ZERO,
        FixedBytes::<32>::ZERO,
        U256::ZERO,
        None, // NO override — old behavior
    )
    .expect("assemble must succeed");

    // Without the override: maker = 303.0303 * 0.33 = 99.999999 trunc to 4+2=6 decimals
    // = 99.999900 → 99_999_900. This is the pre-fix (buggy) value.
    assert_eq!(
        result.order.makerAmount,
        U256::from(99_999_900u64),
        "without override, makerAmount loses one tick: 99_999_900 not 100_000_000"
    );
}

// ── Test 4: FAK is also accepted ──────────────────────────────────────────────

/// Verify that FAK market orders are also accepted by assemble_signable_order_v2.
/// (GTC/GTD/LIMIT should NOT be used for market orders, but assemble itself
/// doesn't validate order_type — the build_v2 caller does.)
#[test]
fn v2_market_fak_order_type_accepted() {
    let result = assemble_signable_order_v2(
        U256::from(1u64),
        Side::Sell,
        dec!(0.60),   // price
        dec!(100.00), // size (shares to sell)
        dec!(0.01),   // minimum_tick_size
        OrderType::FAK,
        false,        // post_only
        || 1u64,
        || PINNED_MS,
        None,
        Address::ZERO,
        SignatureType::Eoa,
        FixedBytes::<32>::ZERO,
        FixedBytes::<32>::ZERO,
        U256::ZERO,   // expiration = 0
        None,         // maker_amount_override: SELL uses default computation
    )
    .expect("FAK market sell must succeed");

    assert!(matches!(result.order_type, OrderType::FAK));
    assert_eq!(result.expiration, U256::ZERO);

    // SELL: maker=shares=100_000_000, taker=shares*price=60_000_000
    assert_eq!(
        result.order.makerAmount,
        U256::from(100_000_000u64),
        "SELL maker = shares"
    );
    assert_eq!(
        result.order.takerAmount,
        U256::from(60_000_000u64),
        "SELL taker = shares * price"
    );
}

// ── Test 5: V1 Market build path is not affected ──────────────────────────────

/// Confirm the V1 market `build` path is untouched (compile-only guard).
/// The V1 path produces `SignableOrder`, not `SignableOrderV2`.
/// This test is structural (doesn't run network calls) — it ensures build_v2
/// compiles independently of the V1 path by importing both types.
#[test]
fn v2_market_v1_types_still_importable() {
    use polymarket_client_sdk::clob::types::{SignableOrder, SignableOrderV2};

    // If this compiles, V1 and V2 types still coexist. No runtime assertion needed.
    let _v1: Option<SignableOrder> = None;
    let _v2: Option<SignableOrderV2> = None;
}
